### ISSUE TITLE
Detect theme file changes and update SW accordingly

### ISSUE THREAD

**Issue by darkwing** [darkwing/wp-sw-cache#14]
If a blogger updates a file that's cached (say they update the image via FTP), the SW wont serve the updated file unless they click "Save changes" in the WPSWC plugin settings.

To make the plugin more dynamic, instead of simply storing the file paths to cache, we could store a checksum with each file and then verify the same checksum upon SW output.  If the checksums don't match up, we update the SW version (name) automatically and thus the problem is solved.

**Comment by darkwing** [comment]
Instead of a checksum we could do `filemtime()` and use that to compare.  Also, we could make this "advanced checking" an option.

**Comment by darkwing** [comment]
@delapuente  mentioned his plugin used a hash for this.

**Comment by darkwing** [comment]
Doing a `wp_hash()` per file on the file contents would work.

**Comment by darkwing** [comment]
The problem with `wp_hash`'ing file contents is we'd need to open potentially dozens (if not hundreds) of files and read their contents; that doesn't sound very performant.

**Comment by delapuente** [comment]
You can rely on the modification date then. I'll do the same with the post last-modified field.

**Comment by darkwing** [comment]
This can be closed when https://github.com/darkwing/wp-sw-cache/pull/31 is merged

**Comment by darkwing** [comment]
https://github.com/darkwing/wp-sw-cache/pull/31
