### ISSUE TITLE
Add tests to service worker

### ISSUE THREAD

**Issue by delapuente** [darkwing/wp-sw-cache#17]
Isolate the API into a singleton object and run test on them. You can see working a setup in:
https://github.com/delapuente/wp-offline-content

**Comment by darkwing** [comment]
Test framework is setup, no tests in though

**Comment by darkwing** [comment]
Will add more moving forward but basics are in:  https://github.com/darkwing/wp-sw-cache/commit/7ef58b68f4dc3b328ba1a16bd633db28c6dd905b
