### ISSUE TITLE
option to "select all" files in "Theme Files to Cache"

### ISSUE THREAD

**Issue by mykmelez** [darkwing/wp-sw-cache#19]
It'd be nice to be able to "select all" files in the list of "Theme Files to Cache," for the case where you simply want to cache everything you possibly can. It's also helpful if you're caching most files, because then you can "select all" and selectively remove items.

**Comment by darkwing** [comment]
Added here: https://github.com/darkwing/wp-sw-cache/commit/56e27e06a553cd03eabf269b143eb43aa9838f1d
