### ISSUE TITLE
Determine which files to cache

### ISSUE THREAD

**Issue by darkwing** [darkwing/wp-sw-cache#29]
We need a logical way to determine which theme files to cache and which to ignore.

**Comment by darkwing** [comment]
Some very rough logic:

1.  Cache all "main level" CSS files
2.  Cache all "main level" JS files

**Comment by digitarald** [comment]
## + Don't Cache
 - `ie\d*.css`

**Comment by darkwing** [comment]
This will be a continued battle.  I have a "framework" in place for this so I'm closing this ticket; we can add logic as wanted.
