### ISSUE TITLE
More Efficiently Purge Cache

### ISSUE THREAD

**Issue by darkwing** [darkwing/wp-sw-cache#34]
At the moment, when the hash version changes, I'm purging the entire cache, even if it's just one file that has changed.  We should add more advanced logic to replace only individual files in the SW cache, not purge the entire thing.

**Comment by darkwing** [comment]
@delapuente Did you mention in today's standup that you had a solution for this, or were working on one?  I'd love your insight/help!

**Comment by delapuente** [comment]
https://github.com/delapuente/wp-offline-content/pull/5/files

**Comment by darkwing** [comment]
Boom:  https://github.com/darkwing/wp-sw-cache/commit/be7873a64c2d122cefb56fe67a701b7aac954ecb
