### ISSUE TITLE
on_activate isn't run when the plugin is updated

### ISSUE THREAD

**Issue by marco-c** [darkwing/wp-sw-cache#49]
I was mistaken too in my plugin.

**Comment by darkwing** [comment]
I see you have this:  https://github.com/mozilla/wp-web-push/pull/154/files

What is the idea here?

**Comment by marco-c** [comment]
I basically check the version every time the plugin is loaded, if the version differs, I run the update procedure.

**Comment by darkwing** [comment]
Yes, I don't have an update/version check yet.  Todo: https://codex.wordpress.org/Function_Reference/get_plugin_data

**Comment by marco-c** [comment]
Oh, ok, I thought the code in on_activation was meant to handle updates.
