### ISSUE TITLE
Service Worker Lingers When it Shouldn't

### ISSUE THREAD

**Issue by darkwing** [darkwing/wp-sw-cache#63]
To repeat:

1.  Activate and enable the plugin, check `debug` so messages will display in the console
2.  Add some files to cache, save
3.  Visit a page on the site so items get cached
4.  Disable the 'enable' checkbox in admin
5.  Visit page on the site -- you'll still see the debug messages.  WTF
6.  Deactivate the plugin in admin
5.  Visit page on the site -- you'll still see the debug messages.  WTF

- I only have my plugin enabled/disabled at a given time.

**Comment by darkwing** [comment]
Side note the SW address 404s if my plugin is activated by not enabled so I've opened this: 

https://github.com/darkwing/wp-sw-cache/compare/disabled-sw?expand=1

**Comment by delapuente** [comment]
>> 4. Disable the 'enable' checkbox in admin
5. Visit page on the site -- you'll still see the debug messages. WTF

Probably because the former SW was still active. Try to reload after step 5.
